In [1]:
import pandas as pd

In [109]:
path='C://Users/sergi/Documents/GitHub/py-villacres-lizano-sergio-wladimir/Examen/articulos.csv'

In [129]:
lista = pd.read_csv(
        path
        )
lista

                                      Productos
0           LUBRICANTES PARA MOTORES A GASOLINA
1         LUBRICANTES PARA MOTORES DE 4 TIEMPOS
2           LUBRICANTES PARA MOTORES A GASOLINA
3             LUBRICANTES PARA MOTORES A DIESEL
4        LUBRICANTES PARA MOTORES A GAS NATURAL
5                    LUBRICANTES PARA 2 TIEMPOS
6              LUBRICANTES PARA MOTORES MARINOS
7   LUBRICANTES PARA TRANSMISIONES AUTOMOTRICES
8                  LUBRICANTES PARA HIDRÁULICOS
9                     LUBRICANTES PARA TURBINAS
10         LUBRICANTES PARA SISTEMAS NEUMATICOS
11                LUBRICANTES PARA INDUSTRIALES
12          ACEITE DIELÉCTRICO/ TRANSFORMADORES
13                                       GRASAS
14                         PRODUCTOS ESPECIALES

In [130]:
nueva_lista =lista.Productos.apply(lambda x: pd.Series(x.split(' ')))
nueva_lista

,0,1,2,3,4,5
0,LUBRICANTES,PARA,MOTORES,A,GASOLINA,NaN
1,LUBRICANTES,PARA,MOTORES,DE,4,TIEMPOS
2,LUBRICANTES,PARA,MOTORES,A,GASOLINA,NaN
3,LUBRICANTES,PARA,MOTORES,A,DIESEL,NaN
4,LUBRICANTES,PARA,MOTORES,A,GAS,NATURAL
5,LUBRICANTES,PARA,2,TIEMPOS,NaN,NaN
6,LUBRICANTES,PARA,MOTORES,MARINOS,NaN,NaN
7,LUBRICANTES,PARA,TRANSMISIONES,AUTOMOTRICES,NaN,NaN
8,LUBRICANTES,PARA,HIDRÁULICOS,NaN,NaN,NaN
9,LUBRICANTES,PARA,TURBINAS,NaN,NaN,NaN
10,LUBRICANTES,PARA,SISTEMAS,NEUMATICOS,NaN,NaN
11,LUBRICANTES,PARA,INDUSTRIALES,NaN,NaN,NaN
12,ACEITE,DIELÉCTRICO/,TRANSFORMADORES,NaN,NaN,NaN
13,GRASAS,NaN,NaN,NaN,NaN,NaN
14,PRODUCTOS,ESPECIALES,NaN,NaN,NaN,NaN

In [131]:
data = pd.DataFrame(columns=('grupo', 'subgrupo'))
grupos=[]
subgrupos=[]

In [132]:
for item, fila in nueva_lista.iterrows():
    if(pd.isnull(fila[1])):
        grupos.append(fila[0])
        subgrupos.append(fila[0])
    elif(pd.isnull(fila[2])):
        grupos.append(fila[0]+' '+fila[1])
        subgrupos.append(fila[0]+' '+fila[1])
    else:
        grupos.append(fila[0])
        valor = len(fila)
        sub=''
        for it in range(2,valor-1,1):
            sub=sub+' '+str(fila[it])
        subgrupos.append(sub)

In [133]:
grupos

['LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'LUBRICANTES',
 'ACEITE',
 'GRASAS',
 'PRODUCTOS ESPECIALES']

In [134]:
subgrupos

[' MOTORES A GASOLINA',
 ' MOTORES DE 4',
 ' MOTORES A GASOLINA',
 ' MOTORES A DIESEL',
 ' MOTORES A GAS',
 ' 2 TIEMPOS nan',
 ' MOTORES MARINOS nan',
 ' TRANSMISIONES AUTOMOTRICES nan',
 ' HIDRÁULICOS nan nan',
 ' TURBINAS nan nan',
 ' SISTEMAS NEUMATICOS nan',
 ' INDUSTRIALES nan nan',
 ' TRANSFORMADORES nan nan',
 'GRASAS',
 'PRODUCTOS ESPECIALES']

In [135]:
serie_grupo = pd.Series(grupos)
serie_subgrupo = pd.Series(subgrupos)

In [136]:
data['grupo']=serie_grupo
data['subgrupo']=serie_subgrupo
data

                   grupo                         subgrupo
0            LUBRICANTES               MOTORES A GASOLINA
1            LUBRICANTES                     MOTORES DE 4
2            LUBRICANTES               MOTORES A GASOLINA
3            LUBRICANTES                 MOTORES A DIESEL
4            LUBRICANTES                    MOTORES A GAS
5            LUBRICANTES                    2 TIEMPOS nan
6            LUBRICANTES              MOTORES MARINOS nan
7            LUBRICANTES   TRANSMISIONES AUTOMOTRICES nan
8            LUBRICANTES              HIDRÁULICOS nan nan
9            LUBRICANTES                 TURBINAS nan nan
10           LUBRICANTES          SISTEMAS NEUMATICOS nan
11           LUBRICANTES             INDUSTRIALES nan nan
12                ACEITE          TRANSFORMADORES nan nan
13                GRASAS                           GRASAS
14  PRODUCTOS ESPECIALES             PRODUCTOS ESPECIALES

In [138]:
data.to_csv('archivo_fin.csv', header=True, index=False)